# Generated by Django 6.0.2 on 2026-02-20 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=250)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=250)),
                ("is_pleasant", models.BooleanField(default=False)),
                ("periodicity", models.PositiveSmallIntegerField(default=1)),
                ("reward", models.CharField(blank=True, max_length=250, null=True)),
                ("execution_time", models.PositiveSmallIntegerField()),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_to",
                        to="habits.habit",
                    ),
                ),
            ],
        ),
    ]
